<?php
/*
 * JDP store funnel events — where do buyers drop off?
 *
 * WHY THIS EXISTS
 * Steven, 2026-09-25: "4 imprint does 1 billion in revenue and we do not!" 4imprint decides with
 * data. Our 583 company stores recorded NOTHING: not how many people opened a store, searched,
 * found nothing, opened a product, added it, reached checkout or sent a request. Every UX decision
 * so far was made by reading code and screenshots. This is the smallest honest instrument: an
 * anonymous count of the steps of the funnel, per store, per day.
 *
 * ENDPOINTS
 *   POST {kit, e, sid, q?, n?, k?}           -> 204   (sendBeacon; the store never waits on it)
 *   GET  ?report=1&days=7[&kit=]&key=<k>      -> JSON funnel report
 *   GET  ?report=1&html=1&key=<k>             -> the same report as a readable page
 *   GET  ?send=1                              -> emails a report link to steven@justdealspromotions.com
 *
 * WHO CAN READ IT
 * The key is generated by this server on first use and kept above the document root. It is not in
 * the (public) deploy repo and no one ever types it: the server emails a link carrying it to ONE
 * fixed address, through the FormSubmit relay the store already uses for quote requests. Anyone may
 * ask for a link to be sent -- only Steven receives it. At most one email an hour; and the first
 * event after seven quiet days sends the weekly digest on its own, so the numbers arrive without
 * anyone remembering to look.
 *
 * PRIVACY
 * No names, no emails, no IP stored. `sid` is a random per-tab id the browser makes up. Search text
 * is kept (it is the single most useful thing to learn) but anything that looks like an email
 * address or a phone number is removed before it is written.
 *
 * STORAGE  <account>/jdp-board-data/_events/<YYYY-MM-DD>.jsonl, above the document root and outside
 * the GitHub->SiteGround mirror, beside the boards this same host already keeps.
 */
declare(strict_types=1);
header('Cache-Control: no-store');
header('X-Content-Type-Options: nosniff');

const EV_OK        = ['view','search','search0','sheet','add','board','checkout','sent','source','aisle','alt','added_go','board_quote','hero_programs','hero_ask','faq_ask'];
const EV_PER_HOUR  = 900;        // per IP; a real buyer sends a few dozen

function data_root(): string { return dirname(__DIR__, 3) . '/jdp-board-data'; }
function ensure_dir(string $d): bool { return is_dir($d) || (@mkdir($d, 0775, true) && is_dir($d)); }
function slug(?string $s, int $max = 60): string {
    $s = strtolower(trim((string)$s));
    return preg_match('/^[a-z0-9][a-z0-9_\-]{0,' . ($max - 1) . '}$/', $s) ? $s : '';
}
function clean_q(?string $q): string {
    $q = mb_substr(trim((string)$q), 0, 80);
    $q = preg_replace('/\S+@\S+/', '[email]', $q);                  // never keep an address
    $q = preg_replace('/\+?\d[\d\s\-().]{6,}\d/', '[number]', $q);   // or a phone number
    return mb_strtolower(preg_replace('/\s+/', ' ', $q));
}
function rate_ok(): bool {
    $dir = data_root() . '/_rate';
    if (!ensure_dir($dir)) return true;
    $f = $dir . '/ev_' . substr(sha1((string)($_SERVER['REMOTE_ADDR'] ?? '0') . '|ev'), 0, 24) . '.json';
    $now = time(); $hits = [];
    if (is_file($f)) { $d = json_decode((string)@file_get_contents($f), true); if (is_array($d)) $hits = $d; }
    $hits = array_values(array_filter($hits, static fn($t) => is_int($t) && $t > $now - 3600));
    if (count($hits) >= EV_PER_HOUR) return false;
    $hits[] = $now; @file_put_contents($f, json_encode($hits), LOCK_EX);
    return true;
}

/* ---- read: the funnel report, for Steven only ------------------------------------------------ */
const REPORT_TO = 'steven@justdealspromotions.com';
function secret(): string {
    $f = data_root() . '/_events/.key';
    if (is_file($f)) { $k = trim((string)@file_get_contents($f)); if (strlen($k) >= 32) return $k; }
    ensure_dir(dirname($f));
    $k = bin2hex(random_bytes(24));
    @file_put_contents($f, $k, LOCK_EX); @chmod($f, 0600);
    return $k;
}
function key_ok(): bool { $k = (string)($_GET['key'] ?? ''); return $k !== '' && hash_equals(secret(), $k); }
function report_url(int $days = 7): string {
    return 'https://justdealspromotions.com/kits/_api/events.php?report=1&html=1&days=' . $days . '&key=' . secret();
}
/* One email, one fixed recipient, through the relay the store already uses. */
function send_link(string $why, array $summary = []): bool {
    $stamp = data_root() . '/_events/.sent';
    if (is_file($stamp) && filemtime($stamp) > time() - 3600) return false;      // one an hour
    $lines = [$why, '', 'Open the report (last 7 days): ' . report_url(7), 'Last 30 days: ' . report_url(30)];
    if ($summary) { $lines[] = ''; foreach ($summary as $k => $v) $lines[] = str_pad($k, 12) . ' ' . $v; }
    $body = json_encode(['_subject' => 'Company stores - funnel report', '_template' => 'box', '_captcha' => 'false',
        'report' => implode("\n", $lines)]);
    $ctx = stream_context_create(['http' => ['method' => 'POST', 'timeout' => 10, 'ignore_errors' => true,
        'header' => "Content-Type: application/json\r\nAccept: application/json\r\nOrigin: https://justdealspromotions.com\r\nReferer: https://justdealspromotions.com/kits/\r\n",
        'content' => $body]]);
    $raw = @file_get_contents('https://formsubmit.co/ajax/' . REPORT_TO, false, $ctx);
    $ok = $raw && strpos($raw, 'true') !== false;
    if ($ok) { ensure_dir(dirname($stamp)); @touch($stamp); }
    return $ok;
}
if (($_SERVER['REQUEST_METHOD'] ?? 'GET') === 'GET') {
    header('Content-Type: application/json; charset=utf-8');
    if (!empty($_GET['send'])) { echo json_encode(['ok' => true, 'sent' => send_link('A funnel report link was requested for the JDP company stores.')]); exit; }
    if (empty($_GET['report'])) { http_response_code(400); echo '{"ok":false}'; exit; }
    if (!key_ok()) { http_response_code(403); echo '{"ok":false,"error":"forbidden"}'; exit; }
    $days = max(1, min(90, (int)($_GET['days'] ?? 7)));
    $only = slug($_GET['kit'] ?? '');
    $steps = EV_OK; $tot = array_fill_keys($steps, 0); $sess = []; $kits = []; $q = []; $q0 = []; $prod = []; $byDay = [];
    for ($i = 0; $i < $days; $i++) {
        $day = gmdate('Y-m-d', time() - 86400 * $i);
        $f = data_root() . "/_events/$day.jsonl";
        if (!is_file($f)) continue;
        $fh = @fopen($f, 'r'); if (!$fh) continue;
        while (($line = fgets($fh)) !== false) {
            $r = json_decode($line, true); if (!is_array($r)) continue;
            if ($only && ($r['kit'] ?? '') !== $only) continue;
            $e = $r['e'] ?? ''; if (!isset($tot[$e])) continue;
            $tot[$e]++; $byDay[$day][$e] = ($byDay[$day][$e] ?? 0) + 1;
            $sid = ($r['kit'] ?? '') . '|' . ($r['sid'] ?? '');
            $sess[$sid][$e] = 1; if ($e === 'search0') $sess[$sid]['search'] = 1;   // a failed search is still a search
            $k = $r['kit'] ?? ''; $kits[$k][$e] = ($kits[$k][$e] ?? 0) + 1;
            if ($e === 'search')  { $t = $r['q'] ?? ''; if ($t !== '') $q[$t]  = ($q[$t]  ?? 0) + 1; }
            if ($e === 'search0') { $t = $r['q'] ?? ''; if ($t !== '') $q0[$t] = ($q0[$t] ?? 0) + 1; }
            if (in_array($e, ['sheet', 'add'], true) && !empty($r['k'])) { $prod[$r['k']][$e] = ($prod[$r['k']][$e] ?? 0) + 1; }
        }
        fclose($fh);
    }
    /* The funnel counts SESSIONS that reached each step, so one buyer opening ten products is one. */
    $funnel = array_fill_keys(['view', 'search', 'sheet', 'add', 'checkout', 'sent'], 0);
    foreach ($sess as $s) { foreach ($funnel as $st => $_) { if (!empty($s[$st])) $funnel[$st]++; } }
    arsort($q); arsort($q0);
    uasort($kits, static fn($a, $b) => ($b['view'] ?? 0) <=> ($a['view'] ?? 0));
    uasort($prod, static fn($a, $b) => ($b['add'] ?? 0) <=> ($a['add'] ?? 0) ?: ($b['sheet'] ?? 0) <=> ($a['sheet'] ?? 0));
    $rep = ['ok' => true, 'days' => $days, 'kit' => $only ?: null, 'sessions' => count($sess),
        'funnel_sessions' => $funnel, 'events' => $tot, 'by_day' => $byDay,
        'top_searches' => array_slice($q, 0, 40, true), 'zero_result_searches' => array_slice($q0, 0, 40, true),
        'top_products' => array_slice($prod, 0, 30, true), 'kits' => array_slice($kits, 0, 60, true)];
    if (empty($_GET['html'])) { echo json_encode($rep, JSON_UNESCAPED_SLASHES); exit; }
    header('Content-Type: text/html; charset=utf-8');
    header('X-Robots-Tag: noindex');
    $h = fn($x) => htmlspecialchars((string)$x, ENT_QUOTES);
    $labels = ['view' => 'Opened a store', 'search' => 'Searched', 'sheet' => 'Opened a product', 'add' => 'Added to a board',
        'checkout' => 'Opened checkout', 'sent' => 'Sent a request'];
    $top = max(1, $funnel['view']);
    echo '<!doctype html><meta charset=utf-8><meta name=viewport content="width=device-width,initial-scale=1"><meta name=robots content=noindex>'
       . '<title>Store funnel</title><style>body{font:15px/1.5 system-ui,sans-serif;max-width:860px;margin:32px auto;padding:0 20px;color:#1b1b1b}'
       . 'h1{font-size:24px;margin:0 0 4px}.m{color:#777;margin:0 0 22px}.r{display:grid;grid-template-columns:170px 1fr 70px 60px;gap:10px;align-items:center;margin:7px 0}'
       . '.b{height:22px;background:#e11d2e;border-radius:4px}.n{text-align:right;font-weight:700}.p{color:#777;text-align:right}'
       . 'table{border-collapse:collapse;width:100%;margin:6px 0 24px}td{padding:6px 8px;border-bottom:1px solid #eee}td:last-child{text-align:right;font-weight:700}'
       . 'h2{font-size:16px;margin:26px 0 6px}</style>'
       . '<h1>Company stores &mdash; where buyers go</h1><p class=m>Last ' . $days . ' days' . ($only ? ' &middot; ' . $h($only) : ' &middot; all stores')
       . ' &middot; ' . count($sess) . ' sessions &middot; counted once per visit</p>';
    foreach ($labels as $k => $lab) { $v = $funnel[$k] ?? 0;
        echo '<div class=r><span>' . $lab . '</span><div class=b style="width:' . max(1, round(100 * $v / $top)) . '%"></div><span class=n>' . $v . '</span><span class=p>' . round(100 * $v / $top) . '%</span></div>'; }
    $tbl = function (string $title, array $rows, int $max = 25) use ($h) {
        echo '<h2>' . $title . '</h2><table>'; $i = 0;
        foreach ($rows as $k => $v) { if ($i++ >= $max) break; echo '<tr><td>' . $h($k) . '</td><td>' . $h(is_array($v) ? json_encode($v) : $v) . '</td></tr>'; }
        if (!$rows) echo '<tr><td>Nothing yet</td><td></td></tr>';
        echo '</table>'; };
    $tbl('Searches that found NOTHING &mdash; what buyers want and cannot find', $q0);
    $tbl('Top searches', $q);
    /* product NAMES, from the catalogue this same host serves, not internal keys */
    $names = []; $cj = @json_decode((string)@file_get_contents(dirname(__DIR__) . '/_catalog/catalog.json'), true);
    if (is_array($cj)) foreach (($cj['items'] ?? []) as $it) { if (!empty($it['key'])) $names[$it['key']] = trim(($it['name'] ?? '') . ' · ' . ($it['brand'] ?? $it['sku'] ?? ''), ' ·'); }
    $pv = []; foreach ($prod as $k => $v) $pv[$names[$k] ?? $k] = ($v['sheet'] ?? 0) . ' opened · ' . ($v['add'] ?? 0) . ' added';
    $tbl('Products', $pv);
    $kv = []; foreach ($kits as $k => $v) $kv[$k] = ($v['view'] ?? 0) . ' views · ' . ($v['add'] ?? 0) . ' adds · ' . ($v['sent'] ?? 0) . ' sent';
    $tbl('Stores', $kv, 60);
    exit;
}

/* ---- write: one anonymous event --------------------------------------------------------------- */
$raw = file_get_contents('php://input', false, null, 0, 4096) ?: '';
$in = json_decode($raw, true);
if (!is_array($in)) { http_response_code(204); exit; }
$kit = slug($in['kit'] ?? ''); $e = (string)($in['e'] ?? '');
$sid = preg_match('/^[a-z0-9]{8,32}$/', (string)($in['sid'] ?? '')) ? (string)$in['sid'] : '';
if ($kit === '' || $sid === '' || !in_array($e, EV_OK, true) || !rate_ok()) { http_response_code(204); exit; }
$rec = ['t' => time(), 'kit' => $kit, 'e' => $e, 'sid' => $sid];
if (isset($in['q'])) $rec['q'] = clean_q((string)$in['q']);
if (isset($in['n'])) $rec['n'] = max(0, min(100000, (int)$in['n']));
if (isset($in['k'])) { $k = slug((string)$in['k'], 60); if ($k) $rec['k'] = $k; }
$dir = data_root() . '/_events';
/* The weekly digest sends itself: the first event after seven days without one. */
$wk = $dir . '/.digest';
if (!is_file($wk) || filemtime($wk) < time() - 7 * 86400) {
    ensure_dir($dir); @touch($wk);
    if (is_file($wk . '.first')) { send_link('Your weekly funnel report for the JDP company stores is ready.'); }
    else { @touch($wk . '.first'); }                 // no digest for the very first event ever
}
if (ensure_dir($dir)) {
    @file_put_contents($dir . '/' . gmdate('Y-m-d') . '.jsonl', json_encode($rec, JSON_UNESCAPED_SLASHES) . "\n", FILE_APPEND | LOCK_EX);
}
http_response_code(204);
